#!/bin/sh
# Auto-generate .env with random secrets if it doesn't already exist.
# Runs as the first container in the compose stack.

ENV_FILE="/workspace/.env"

if [ -f "$ENV_FILE" ]; then
  echo "[env-init] .env already exists — skipping generation."
  exit 0
fi

echo "[env-init] Generating .env with random secrets..."

JWT_SECRET=$(head -c 64 /dev/urandom | base64 | tr -d '\n/+=')
CSRF_SECRET=$(head -c 32 /dev/urandom | base64 | tr -d '\n/+=')
FIELD_KEY=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)
FILE_KEY=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)
VISION_KEY=$(head -c 32 /dev/urandom | base64 | tr -d '\n/+=')

cat > "$ENV_FILE" <<EOF
# Auto-generated by StudyRoomOps on first startup.
# Safe to edit — will not be overwritten on subsequent starts.

JWT_SECRET=${JWT_SECRET}
CSRF_SECRET=${CSRF_SECRET}
FIELD_ENCRYPTION_KEY=${FIELD_KEY}
ENCRYPTION_KEY=${FIELD_KEY}
FILE_ENCRYPTION_KEY=${FILE_KEY}
VISION_INTERNAL_KEY=${VISION_KEY}

SITE_TIMEZONE=America/Los_Angeles
NODE_ENV=production
API_PORT=3001
LOG_LEVEL=info
VISION_WORKER_ENABLED=false
EOF

echo "[env-init] .env written to $ENV_FILE"
